version: "3.8"

services:
  thinknblend:
    build: .
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=0
    volumes:
      - ./input:/app/input
      - ./output:/app/output
      - ./.env:/app/.env
      - ./submodules:/app/submodules
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command:
      [
        "python",
        "main.py",
        "--mode",
        "object",
        "--main_image",
        "input/main_image.jpg",
        "--object_crop",
        "input/object_crop.jpg",
      ]
